import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ShieldCheck, Lock } from 'lucide-react';
import { Input } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { Alert } from '../../components/ui/Alert';

export const MfaPage: React.FC = () => {
  const navigate = useNavigate();
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('Authentication service is not configured yet.');
  };

  return (
    <div className="space-y-6">
      <div className="text-center space-y-2">
        <div className="w-12 h-12 rounded-2xl bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center mx-auto">
          <ShieldCheck className="w-6 h-6" />
        </div>
        <h2 className="text-2xl font-extrabold tracking-tight">Two-Factor Security</h2>
        <p className="text-xs text-slate-600 dark:text-slate-400">
          Enter the multi-factor passcode generated by your authenticator app.
        </p>
      </div>

      {errorMsg && <Alert variant="error">{errorMsg}</Alert>}

      <form onSubmit={handleSubmit} className="space-y-4">
        <Input
          label="MFA Passcode"
          required
          placeholder="6-digit code"
          leftIcon={<Lock className="w-4 h-4" />}
          value={code}
          onChange={e => setCode(e.target.value)}
        />

        <Button variant="primary" size="lg" type="submit" className="w-full justify-center" isLoading={loading}>
          Authenticate Session
        </Button>
      </form>

      <div className="pt-4 border-t border-slate-100 dark:border-slate-800 text-center text-xs">
        <Link to="/login" className="font-bold text-indigo-600 dark:text-indigo-400 hover:underline">
          Return to Sign In
        </Link>
      </div>
    </div>
  );
};
